name: Python CI

on: [push]

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run tests
        working-directory: myapp
        run: |
          python -m unittest discover

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit SAST scan
        working-directory: myapp
        run: bandit -r .
        
      - name: Build Docker Image
        working-directory: myapp
        run: docker build -t securecalc .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy Scan
        working-directory: myapp
        run: trivy fs .
